#!/usr/bin/env bash
# install nging on web-01 server and make some configuration
sudo apt-get update
sudo apt-get -y install nginx
sudo chmod -R 755 /var/www
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
