#!/usr/bin/env bash
# install and configure nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
