#!/usr/bin/env bash
# install nging on web-01 server and make some configuration
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" >  tee /var/www/index/index.nginx-debian.html
sudo service nginx restart
