#!/usr/bin/env bash
# script
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" >> /usr/share/nginx/html/index.html
printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /usr/share/nginx/html;
        index index.html index.htm

        location / redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
        }
} >> /etc/nginx/sites-available-default
service nginx restart
