#!/usr/bin/env bash
# script
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
printf %s "server {
        listen 80;
        listen [::]:80 default_server;
        root /usr/share/nginx/html;
        index index.html index.htm

        location / redirect_me {
                return 301 http://www.youtube.com/;
        }
}" > /etc/nginx/sites-available/default
service nginx restart
