#!/usr/bin/env bash
# script that configure nginx server .........
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
printf %s "server {
        listen 80;
        listen [::]:80 default_server;
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        location /redirect_me {
                return 301 http://youtube.com/watch?v=QH2-TGUlwu4;
        }
        error_page 404 /404.html;
        location /404 {
        root /usr/share/nginx/html;
        internal;
        }
}"  > /etc/nginx/sites-available/default
service nginx start
