#!/usr/bin/env bash
#Creates the file /var/run/holbertonscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"; rm -f /var/run/holberton.pid; kill -9 $$' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/holbertonscript.pid; kill -9 $$' SIGQUIT
while ((1)); do
	echo "To infinity and beyond"
	sleep 2
done
