#!/usr/bin/env bash
# script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Holberton School for the other iterations
var="Holberton School"
var1="bad luck"
var2="good luck"
i=1
while ((i<11)); do
	if ((i==4))
	then
		echo "$var1"
	elif ((i==8))
	then
		echo "$var2"
	else
  		echo "$var"
	fi
	((i++))
done
