#!/usr/bin/env bash
#  Nginx is running as the nginx user.
pkill nginx
chown nginx:nginx /etc/nginx/nginx.conf
chmod -R 770 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
